[project]
name = "lingus-web"
version = "0.0.1"
description = "Web interface for Lingus"
requires-python = ">=3.12"
dependencies = [
    "fastapi==0.115.12",
    "python-multipart==0.0.20",
    "uvicorn==0.34.1",
]
